server:
  servlet:
    context-path: /

spring:
  application:
    name: sample
  profiles:
    active: @profileActive@

rest:
  baseDtoPackage: com.threadclub.sample.service.dto
  baseVoPackage: com.threadclub.sample.controller.vo

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%15thread]){faint} %clr(%-50.50(%logger{39}.%method:%-3line)){cyan} %clr(-){faint} %msg%n"
  file: ../logs/sample/sample.log
  file.max-history: 30
  level:
    com.threadclub.sample: info
