server:
  port: 9103

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC
    username: root
    password: 123456
  output:
    ansi:
      enabled: always

logging:
  level:
    com.threadclub.sample: info
