server:
  port: 9103

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC
    username: root
    password: 123456

logging:
  level:
    com.threadclub.sample: info